[package]
name = "price_tracker"
version = "0.1.0"
edition = "2021"

[dependencies]
reqwest = { version = "0.11", features = ["blocking", "json"] }
scraper = "0.12"
tokio = { version = "1", features = ["full"] }
serde = "1.0"
serde_json = "1.0"
lettre = "0.10"
dotenv = "0.15"
chrono = "0.4"
